apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-holodeck
  template:
    metadata:
      labels:
        app: hello-holodeck
    spec:
      containers:
      - name: web
        image: nginxdemos/hello
        ports:
        - containerPort: 80
