---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-test-secret
  namespace: default
spec:
  encryptedData:
    db-password: AgCQukej9/sz2aE61abxXI1ThSZd/4IM3EAqFx33ERWI04+Yy0QmAT0iJnDYhVPBOz1e2XBk3kVTGsA/Ko9LM9Xka2364+16yo8hRQ03oZrnq28LlnaPaQXPCl+0BE7IJwsKGrq+Jiuw3156H2AqV7A2V3TYQhRoW4ROhMchK3Prb97XOCRDxbW3cxl55g/ICRfPt6jqs3yRsFmexbWXAwQDk0vZ+tECCh9Hs8C+BRMT2xBLQ4dW7hMOQtcgplahSKs0+l+vfTFf1l4jpx4rYGTrv6ZuU9YaWIJti8sPkhOfJX1ZQvSfPWNKsGn8lNtnePEMWzI6zNGFW5oz/vxOnvrYeoJV5RD92DAdQ6XfdOLTot0+ot6KnWj7OL64xA8wkl84GEGwhaad1EBll9jaljurny+98yuYhQTRobBoP50+sNj4eVwVmctY+PlAOdDG7ZW2PfsPYb4QfU8sYe07OzIwQjkF1AklUPWl7/WCAuWqQO8l3Souxk67uEzmjvFpH14cfVIbv4CAFmfU4QwHKci4iK4K5C50CfjPdXbaYWBK7V44KNuEtlnIAsCD8nj3jLgCc2TgLK6uqVb/57C5Gm5MqJxyDPiX25J0S6Xiwhs06M1Fg262BJVk0pdK7/efNHegRrC9+0eW4hvk1GlniHpH/IrgY+qGKIFY9/y93Egg7uCuO7AgAszzMlRlFcvrgVu8vvD6v3sU79bXRmTBioLaK6YufQ1JB3sKMwUoMA==
  template:
    metadata:
      name: my-test-secret
      namespace: default
